[package]
name = "smtif-bitwuzla"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
logicrs = { path = "../logicrs", version = "0.6.0" }
giputils = { path = "../giputils", version = "0.3.5" }

[build-dependencies]
giputils = { path = "../giputils", version = "0.3.5" }
